apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-deployment
  labels:
    app: custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: shark
        env:
          TF_VAR_access_key: ${{ secrets.AWS_USR_ACCESS_KEY }}
          TF_VAR_secret_key: ${{ secrets.AWS_USR_SECRET_KEY }}
        image: mkdhabale/shark-deployment
        ports:
        - containerPort: 8080