apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: custom
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 300808